# Generated by Django 3.1.6 on 2021-04-05 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category_image', models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='')),
                ('category_favicon_icon', models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
                ('parent_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_category_list', to='product.category')),
            ],
        ),
    ]
