# Generated by Django 3.1.6 on 2021-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_favicon_icon',
            field=models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='images/'),
        ),
    ]
