# Generated by Django 3.1.6 on 2021-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, null=True, unique=True)),
                ('currency_icon', models.CharField(max_length=50, null=True, unique=True)),
                ('currency_position', models.CharField(choices=[(1, 'Yes'), (2, 'No')], default='1', max_length=9)),
                ('convertion_rate', models.FloatField()),
                ('default_status', models.CharField(choices=[(1, 'Yes'), (2, 'No')], default='1', max_length=9)),
            ],
        ),
    ]
