# Generated by Django 3.1.6 on 2021-04-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_position',
            field=models.IntegerField(choices=[(0, 'Left'), (1, 'Right')], default='1'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='default_status',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='1'),
        ),
    ]
