# Generated by Django 3.1.6 on 2021-04-11 10:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('invoice_details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('offer', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='1')),
                ('best_sale', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default='1')),
                ('review', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('specification', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('offer_price', models.FloatField(blank=True, max_length=10, null=True)),
                ('default_image', models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='images/')),
                ('image', models.ImageField(default='dummy-profile-pic-male1.webp', null=True, upload_to='images/')),
                ('sell_price', models.FloatField(blank=True, max_length=10, null=True)),
                ('supplier_price', models.FloatField(blank=True, max_length=10, null=True)),
                ('product_model', models.CharField(blank=True, max_length=30, null=True)),
                ('video_link', models.CharField(blank=True, max_length=30, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_brand', to='product.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_category', to='product.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplier_info', to='product.supplier')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_unit_measurement', to='product.unit')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_variant', to='product.variant')),
            ],
        ),
    ]
